from pathlib import Path
import re, html, zipfile
root=Path('/mnt/data/v47work')
base='https://preparacion-practica.biscottodellasera20.workers.dev/'

def page(slug,title,desc,crumbs,h1,eyebrow,lead,body,source_links):
    bc='<span>›</span>'.join([])
    crumb_html='<a href="index.html">Inicio</a>'
    for name,href in crumbs:
        crumb_html += f'<span>›</span><a href="{href}">{html.escape(name)}</a>'
    crumb_html += f'<span>›</span><span>{html.escape(h1)}</span>'
    sources='<div class="source"><strong>Fuentes y revisión</strong><ul>' + ''.join(f'<li><a href="{u}" target="_blank" rel="noopener">{html.escape(n)}</a></li>' for n,u in source_links) + '</ul><p class="note-small">Revisado: octubre de 2026. Las recomendaciones de autoridades pueden cambiar; ante una emergencia concreta, sigue sus instrucciones.</p></div>'
    s=f'''<!doctype html><html lang="es"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>{html.escape(title)} | Preparación Práctica</title><meta name="description" content="{html.escape(desc)}"><link rel="canonical" href="{base}{slug}"><link rel="stylesheet" href="styles.css"><meta property="og:type" content="article"><meta property="og:title" content="{html.escape(title)}"><meta property="og:description" content="{html.escape(desc)}"><meta property="og:url" content="{base}{slug}"><meta name="twitter:card" content="summary"></head><body><header class="site-header"><a class="brand" href="index.html"><span>Preparación</span> Práctica</a><button class="menu-toggle" aria-label="Abrir menú" aria-expanded="false">☰</button><nav class="nav" aria-label="Navegación principal"><a href="index.html">Inicio</a><a href="empieza-aqui.html">Empieza aquí</a><a href="situaciones.html">Situaciones</a><a href="necesidades.html">Necesidades</a><a href="productos.html">Productos</a><a href="test.html">Test</a><a href="mapas.html">Mapas</a></nav></header><main><div class="container breadcrumb">{crumb_html}</div><section class="page-hero"><div class="container"><p class="eyebrow">{html.escape(eyebrow)}</p><h1>{html.escape(h1)}</h1><p class="lead">{lead}</p></div></section><section class="section"><div class="container">{body}{sources}</div></section></main><p class="affiliate-note container">Algunos enlaces pueden ser de afiliación. Consulta <a href="afiliacion.html">cómo funciona</a>.</p><footer class="footer"><div class="footer-grid"><div><strong>Preparación Práctica</strong><p>Preparación sencilla para cortes de servicios y situaciones inesperadas.</p></div><div><strong>Recursos</strong><div class="footer-links"><a href="72-horas.html">72 horas</a><a href="checklist-72-horas.html">Checklist 72 horas</a><a href="plan-hogar.html">Plan de hogar</a><a href="productos.html">Productos</a></div></div><div><strong>Sobre la web</strong><div class="footer-links"><a href="sobre.html">Quiénes somos</a><a href="aviso-legal.html">Aviso legal</a><a href="afiliacion.html">Afiliación</a><a href="como-elegimos-productos.html">Cómo elegimos</a><a href="privacidad.html">Privacidad</a><a href="cookies.html">Cookies</a><a href="contacto.html">Contacto y correcciones</a></div></div><small>España · Información orientativa. Ante una emergencia concreta, sigue siempre las instrucciones de las autoridades competentes.</small></div></footer><script src="script.js"></script></body></html>'''
    (root/slug).write_text(s,encoding='utf-8')

def h2(t): return f'<h2>{t}</h2>'
def p(t): return f'<p>{t}</p>'
def ul(items): return '<ul class="check-list">'+''.join(f'<li>{x}</li>' for x in items)+'</ul>'

page('que-hacer-si-se-va-la-luz.html','Qué hacer si se va la luz en casa','Pasos claros para comprobar un apagón, actuar con seguridad, ahorrar batería y saber cuándo pedir ayuda.',[], 'Qué hacer si se va la luz en casa','APAGÓN · PASOS PRÁCTICOS','Qué comprobar primero, qué evitar y cómo organizar las primeras horas sin electricidad.',
     '<div class="notice"><strong>Primero: seguridad.</strong> No necesitas resolverlo todo de golpe. Comprueba el alcance del corte, ilumina de forma segura y busca información fiable.</div>'+h2('1. Comprueba si el corte es solo en tu vivienda')+p('Mira si la iluminación y los servicios eléctricos fallan también en zonas comunes o viviendas cercanas. Si parece limitado a tu vivienda, revisa el cuadro eléctrico solo hasta donde puedas hacerlo con seguridad y sin manipular una instalación que no conoces.')+p('Si hay olor a quemado, humo, chispas o señales de una avería peligrosa, no continúes comprobando la instalación por tu cuenta. Aléjate de la zona de riesgo y utiliza los servicios de emergencia cuando corresponda.')+h2('2. Si el apagón afecta a la zona')+ul(['Reduce el uso del móvil a lo necesario y activa el ahorro de batería.','Busca información en canales oficiales y en tu distribuidora cuando exista información de la incidencia.','No abras innecesariamente el frigorífico o el congelador.','Comprueba si alguien del hogar necesita asistencia especial por depender de electricidad.'])+h2('3. ¿A quién llamo?')+p('La CNMC distingue entre distribuidora y comercializadora. Las averías de red y los cortes corresponden a la distribuidora; cuestiones de contrato, tarifa o facturación corresponden a la comercializadora. En tu factura o contrato encontrarás los contactos correspondientes.')+p('La CNMC publica además información de contacto de distribuidores y explica el procedimiento de reclamación cuando una incidencia no se resuelve.')+h2('4. Cuida la iluminación y la batería')+ul(['Utiliza la iluminación que ya tengas preparada y evita desplazarte a oscuras.','Mantén una linterna accesible, no guardada en un lugar que solo puedas encontrar con luz.','Ahorra batería del teléfono y reserva una parte para comunicaciones importantes.'])+h2('5. Si dura horas')+p('Pasa de la improvisación a tu plan: agua, alimentación, medicación/necesidades personales, comunicación e información. Si el corte se prolonga, utiliza tu checklist de 72 horas.')+p('<a class="btn primary" href="checklist-72-horas.html">Abrir checklist de 72 horas →</a>')+p('<a href="productos-apagon.html">Ver las necesidades de un apagón →</a> · <a href="guia-compra-apagon.html">Qué comprar para un apagón →</a>'),
     [('CNMC — Comercialización y suministro eléctrico','https://www.cnmc.es/facil-para-ti/que-hace-la-cnmc-para-consumidores/comercializacion-y-suministro-electrico'),('CNMC — Información para consumidores y distribuidores','https://www.cnmc.es/ambitos-de-actuacion/energia/mercado-electrico')])

page('comida-en-la-nevera-durante-un-apagon.html','Qué hacer con la comida de la nevera durante un apagón','Qué hacer con frigorífico y congelador después de un corte de luz, siguiendo las recomendaciones de AESAN.',[], 'Qué hacer con la comida de la nevera durante un apagón','APAGÓN · ALIMENTOS','La regla más importante es mantener las puertas cerradas y valorar los alimentos según el tiempo y su temperatura.',
     '<div class="notice"><strong>No pruebes la comida para comprobar si está buena.</strong> AESAN indica que no hay que confiar únicamente en el aspecto u olor y que cada alimento debe valorarse según las condiciones de conservación.</div>'+h2('Frigorífico: menos o más de 4 horas')+p('AESAN señala que, con la puerta mantenida cerrada, en cortes inferiores a 4 horas el frigorífico puede mantener los alimentos por debajo de 5 °C y, en principio, no sería necesario descartarlos por el apagón. En cortes superiores a 4 horas aumenta el riesgo de superar esa temperatura y deben descartarse los alimentos perecederos indicados por AESAN, entre ellos carne, pollo, pescado, huevos, leche, queso fresco y sobras.')+h2('Frutas, verduras y alimentos no perecederos')+p('Las frutas y verduras enteras pueden mantenerse si conservan las condiciones de frescura habituales. Las frutas y verduras cortadas y las ensaladas preparadas tienen un tratamiento distinto y AESAN recomienda descartarlas en el supuesto de superar las condiciones indicadas. Algunos productos no perecederos que suelen guardarse en el frigorífico no necesitan realmente frío.')+h2('Congelador')+p('AESAN indica que un congelador puede mantener la temperatura de congelación al menos 24–48 horas si no se abre la puerta. Los alimentos pueden volver a congelarse cuando no se han descongelado por completo y conservan cristales de hielo, dureza y sensación de frío. Si no está claro cuánto tiempo han permanecido descongelados, especialmente si ya no están fríos, la recomendación es descartarlos.')+h2('Qué hacer durante el apagón')+ul(['Mantén cerradas las puertas del frigorífico y congelador.','No uses una prueba de olor, aspecto o sabor como única forma de decidir si un alimento es seguro.','Cuando vuelva la luz, revisa los alimentos individualmente y descarta los que no cumplan las condiciones de conservación.'])+p('<a class="btn primary" href="apagon.html">Volver a la guía de apagones →</a>'),
     [('AESAN — ¿Qué hacer con los alimentos del frigorífico y del congelador después del apagón eléctrico? (29/04/2025)','https://www.aesan.gob.es/actualidad/actualidad-noticias/alimentos_refrigerados')])

page('como-saber-si-un-apagon-es-general.html','Cómo saber si un apagón es de tu casa o general','Una comprobación sencilla para distinguir una incidencia doméstica de un corte que afecta a la zona, sin manipular instalaciones peligrosas.',[], 'Cómo saber si un apagón es de tu casa o general','APAGÓN · DIAGNÓSTICO','Empieza por observar el entorno y solo después comprueba tu vivienda si puedes hacerlo con seguridad.',
     '<div class="notice"><strong>No manipules una instalación eléctrica ante humo, olor a quemado, chispas o daños visibles.</strong> En esos casos, prioriza la seguridad.</div>'+h2('Señales de que afecta a más viviendas')+ul(['También están apagadas las zonas comunes del edificio o el alumbrado próximo.','Los vecinos tienen el mismo problema.','La distribuidora informa de una incidencia en la zona.'])+h2('Señales de que puede estar limitado a tu vivienda')+ul(['El resto del edificio mantiene la electricidad.','Las zonas comunes funcionan con normalidad.','Solo tu cuadro eléctrico presenta una desconexión visible y no hay señales de riesgo.'])+h2('¿Debo tocar el cuadro eléctrico?')+p('Solo realiza comprobaciones sencillas que conozcas y puedas hacer de forma segura. No abras equipos, no manipules cableado y no intentes reparar una avería eléctrica para la que no tienes conocimientos.')+h2('¿A quién aviso si es una avería?')+p('La CNMC explica que la distribuidora opera la red y resuelve las averías de red, mientras que la comercializadora gestiona el contrato y la facturación. Consulta la factura o contrato para localizar los contactos.')+p('<a href="que-hacer-si-se-va-la-luz.html">Ver qué hacer durante las primeras horas →</a>'),
     [('CNMC — Comercialización y suministro eléctrico','https://www.cnmc.es/facil-para-ti/que-hace-la-cnmc-para-consumidores/comercializacion-y-suministro-electrico')])

page('que-hacer-cuando-vuelve-la-luz.html','Qué hacer cuando vuelve la luz después de un apagón','Comprobaciones básicas al restablecerse la electricidad y cómo revisar el frigorífico, los aparatos y las necesidades del hogar.',[], 'Qué hacer cuando vuelve la luz después de un apagón','APAGÓN · VUELVE LA ELECTRICIDAD','El restablecimiento del suministro no significa que debas encender y revisar todo de golpe.',
     '<div class="notice"><strong>Haz una revisión tranquila.</strong> Comprueba primero que no hay señales de daño y después recupera los servicios esenciales.</div>'+h2('1. Comprueba que no hay señales de riesgo')+ul(['Si detectas humo, olor a quemado, chispas o daños visibles, no continúes con la instalación y busca asistencia adecuada.','Comprueba de forma visual que no hay aparatos claramente dañados antes de utilizarlos.'])+h2('2. Revisa frigorífico y congelador')+p('No des por seguro que todos los alimentos siguen siendo aptos. Utiliza el tiempo del apagón y las condiciones de conservación como referencia y aplica las recomendaciones de AESAN.')+h2('3. Recupera los equipos necesarios')+p('Vuelve a conectar lo necesario de forma ordenada. No es necesario poner en funcionamiento todos los aparatos a la vez si la instalación o la situación aconsejan prudencia.')+h2('4. Recarga y repón')+ul(['Carga teléfonos y baterías externas.','Vuelve a colocar linternas, pilas y materiales en su lugar.','Anota cualquier elemento que haya faltado durante el corte y añádelo a tu plan de preparación.'])+h2('5. Aprende del incidente')+p('Si algo que esperabas tener preparado no estaba disponible, conviértelo en una tarea concreta del plan de hogar. Prepararse mejora más cuando se revisa después de una situación real.')+p('<a class="btn primary" href="plan-hogar.html">Revisar mi plan de hogar →</a>'),
     [('AESAN — alimentos tras un apagón','https://www.aesan.gob.es/actualidad/actualidad-noticias/alimentos_refrigerados'),('CNMC — información para consumidores','https://www.cnmc.es/facil-para-ti/que-hace-la-cnmc-para-consumidores/comercializacion-y-suministro-electrico')])

page('que-meter-en-una-mochila-de-emergencia.html','Qué meter en una mochila de emergencia para 72 horas','Una estructura práctica para preparar una bolsa personal sin convertirla en una lista interminable de productos.',[], 'Qué meter en una mochila de emergencia','PREPARACIÓN · 72 HORAS','La mejor mochila de emergencia es la que puedes localizar, transportar y utilizar de verdad.',
     '<div class="notice"><strong>No existe una mochila universal.</strong> El contenido depende de las personas, necesidades y situaciones de cada hogar.</div>'+h2('Imprescindibles personales')+ul(['Documentación y contactos importantes.','Medicamentos y necesidades personales habituales.','Teléfono y sistema de carga disponible.','Iluminación portátil.','Agua y alimentos adecuados a la persona y a la situación.'])+h2('Según el hogar')+ul(['Elementos específicos para niños o personas dependientes.','Necesidades de mascotas.','Ropa adecuada a la estación.','Elementos de higiene.','Llaves y aquello que necesites para una salida rápida.'])+h2('Cómo prepararla')+ul(['Guárdala en un lugar accesible.','No llenes la mochila con objetos que nunca utilizarías.','Revisa periódicamente caducidades, pilas, medicación y contactos.','Adapta su tamaño al peso que realmente puedas transportar.'])+h2('Una mochila no sustituye al plan del hogar')+p('Una bolsa resuelve parte de las necesidades individuales. El plan del hogar debe incluir además agua, alimentación, comunicación, contactos, punto de encuentro y necesidades específicas.')+p('<a class="btn primary" href="plan-hogar.html">Completar mi plan de hogar →</a>'),
     [('Preparación Práctica — Checklist de preparación 72 horas','checklist-72-horas.html'),('Preparación Práctica — Plan de preparación del hogar','plan-hogar.html'),('Comisión Europea — Preparación','https://commission.europa.eu/topics/preparedness_es')])

# Update index with an SEO/help block before trust section
idx=root/'index.html'; txt=idx.read_text(encoding='utf-8')
marker='<section class="section trust">'
block='''<section class="section"><div class="section-heading"><p class="eyebrow">GUÍAS PRÁCTICAS</p><h2>Respuestas rápidas a preguntas habituales</h2><div class="grid three"><a class="card" href="que-hacer-si-se-va-la-luz.html"><h3>¿Qué hacer si se va la luz?</h3><p>Primeros pasos para comprobar el corte, ahorrar batería y actuar con seguridad.</p></a><a class="card" href="comida-en-la-nevera-durante-un-apagon.html"><h3>¿Qué hago con la comida?</h3><p>Qué recomienda AESAN para frigorífico y congelador.</p></a><a class="card" href="que-meter-en-una-mochila-de-emergencia.html"><h3>¿Qué llevo en una mochila?</h3><p>Una estructura práctica para preparar lo importante sin exceso.</p></a></div></div></section>'''
if marker in txt and block not in txt:
 txt=txt.replace(marker,block+marker)
 idx.write_text(txt,encoding='utf-8')

# Append sitemap URLs before close
sm=root/'sitemap.xml'; st=sm.read_text(encoding='utf-8')
new=['que-hacer-si-se-va-la-luz.html','comida-en-la-nevera-durante-un-apagon.html','como-saber-si-un-apagon-es-general.html','que-hacer-cuando-vuelve-la-luz.html','que-meter-en-una-mochila-de-emergencia.html']
for u in new:
 if f'>{base}{u}</loc>' not in st:
  st=st.replace('</urlset>',f'<url><loc>{base}{u}</loc></url></urlset>')
sm.write_text(st,encoding='utf-8')

# README log
readme=root/'README.md'; r=readme.read_text(encoding='utf-8')
r += '''\n\n## V4.7 — contenido SEO útil\n- Añadidas páginas de intención informativa sobre apagones y mochila de emergencia.\n- Reforzados enlaces internos desde portada.\n- Añadidas fuentes oficiales y fecha de revisión en las nuevas páginas.\n- Sitemap ampliado.\n- Sin nuevos scripts de analítica ni cookies de terceros.\n'''
readme.write_text(r,encoding='utf-8')

# Internal checklist
(root/'CHECKLIST_SEO_V47.md').write_text('''# Checklist SEO V4.7\n\n- [x] Intentos de búsqueda informativa cubiertos sin crear páginas duplicadas.\n- [x] Enlaces internos desde portada a nuevas guías.\n- [x] Canonical por página.\n- [x] Descripciones meta.\n- [x] Sitemap actualizado.\n- [x] Fuentes oficiales visibles en contenido sensible.\n- [x] Fecha de revisión indicada.\n- [x] Sin precios ni stock fijos.\n\n## Próximo bloque\n- Conectar Search Console con consultas reales una vez haya impresiones.\n- Priorizar páginas según consultas reales, no según suposiciones.\n- Incorporar enlaces directos de Awin cuando Decathlon apruebe el programa.\n''',encoding='utf-8')

# Remove old accidental duplicate README versions? Keep.
# Validate local hrefs
files=list(root.glob('*.html'))
missing=[]
for pth in files:
 t=pth.read_text(errors='ignore')
 for href in re.findall(r'href=["\']([^"\'#?]+)',t):
  if href.startswith(('http:','https:','mailto:','tel:','javascript:')): continue
  if not (root/href).exists(): missing.append((pth.name,href))
print('HTML',len(files),'missing',len(missing))
if missing:
 print(missing[:20])

# Zip
out=Path('/mnt/data/preparacion_practica_v47.zip')
with zipfile.ZipFile(out,'w',zipfile.ZIP_DEFLATED) as z:
 for p in root.rglob('*'):
  if p.is_file(): z.write(p,p.relative_to(root))
print(out)
